# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: <%= ENV["NEW_RELIC_KEY"] %>
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1

  # Proxy configuration:
  #proxy:
  #  address: localhost
  #  port: 8080
  #  user: nil
  #  password: nil

# Use this shared block if all your buckets use the same AWS
#   credentials. Can use other values for each bucket, though.
s3_creds: &s3_creds
  access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
#
# Agent Configuration:
#
agents:
  s3:
    - bucket_names: <%= ENV["BUCKETS"] %>
      region: us-east-1
      <<: *s3_creds
